version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.1.0  # Use a compatible Node.js version
    working_directory: ~/repo

jobs:
  test-postman-collection:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
            sudo npm install -g newman
      - run:
          name: Run Postman Collection with Newman
          command: |
            newman run ./server/NewCollection.postman_collection.json \
              
              --reporters cli,junit \
              --reporter-junit-export newman/results.xml

      # Store test results
      - store_test_results:
          path: newman/results.xml
      - store_artifacts:
          path: newman

workflows:
  version: 2
  test:
    jobs:
      - test-postman-collection
