version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2  # Update to match your Node.js version
    working_directory: ~/repo  # Adjust if needed

jobs:
  sonarqube:
    docker:
      - image: cimg/node:18.20.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            cd server
            echo "Sonar branch value is: $CIRCLE_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="." \
              -Dsonar.javascript.file.suffixes=.js \
              -Dsonar.cfile.file.suffixes=.

  newmantest:
    docker:
      - image: cimg/node:18.20.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd server
            npm install
      - run:
          name: Run Newman tests
          command: |
            cd server
            npm run test-api &
      - attach_workspace:
          at: ~/workspace
      - store_test_results:
          path: newman/results.xml
      - store_artifacts:
          path: newman

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
      - newmantest:
          requires:
            - sonarqube
