version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.1.0
    working_directory: ~/repo

jobs:
  test-postman-collection:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: List files in server folder
          command: |
            echo "Checking file structure:"
            find ./server
      - run:
          name: Install Dependencies
          command: |
            npm i
      - run:
          name: Run Postman Collection with Newman
          command: |
            npx newman run "server/NewCollection.postman_collection.json" \
              --reporters cli,junit \
              --reporter-junit-export "newman/results.xml"
      - store_test_results:
          path: newman/results.xml
      - store_artifacts:
          path: newman


workflows:
  version: 2
  test:
    jobs:
      - test-postman-collection
