version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2  # Node.js version, keep as required
    working_directory: ~/repo

jobs:
  sonarqube:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            echo 'export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"' >> $BASH_ENV  # Set JAVA_HOME in environment
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV                   # Ensure Java 17 is in PATH
            source $BASH_ENV  # Reload environment variables
            java -version  # Verify Java 17 is the default
      - run:
          name: Install Sonar Scanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip sonar-scanner.zip -d ~/sonar-scanner
            export PATH=$PATH:~/sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin
      - run:
          name: SonarQube Analysis
          command: |
            cd server
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$CIRCLE_BRANCH" \
              -Dsonar.sources="." \
              -Dsonar.javascript.file.suffixes=.js \
              -Dsonar.cfile.file.suffixes=.

  newmantest:
    docker:
      - image: cimg/node:18.20.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd server
            npm install
      - run:
          name: Run Newman tests
          command: |
            cd server
            npm run test-api &
      - attach_workspace:
          at: ~/workspace
      - store_test_results:
          path: newman/results.xml
      - store_artifacts:
          path: newman

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
      - newmantest:
          requires:
            - sonarqube
